# INITIAL ADMIN DB
# This is the schema of the email module database as of 09/01/2015
DROP TABLE IF EXISTS `nails_email_archive`;
CREATE TABLE `nails_email_archive` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `ref` varchar(10) DEFAULT NULL, `user_id` int(11) unsigned DEFAULT NULL, `user_email` varchar(150) DEFAULT NULL, `sent` datetime DEFAULT NULL, `status` enum('SENT','BOUNCED','OPENED','REJECTED','DELAYED','SOFT_BOUNCED','MARKED_AS_SPAM','CLICKED','FAILED') NOT NULL DEFAULT 'SENT', `type` varchar(50) NOT NULL DEFAULT '', `email_vars` longtext, `internal_ref` int(11) unsigned DEFAULT NULL, `read_count` tinyint(3) unsigned NOT NULL DEFAULT '0', `link_click_count` tinyint(3) unsigned NOT NULL DEFAULT '0', PRIMARY KEY (`id`), KEY `user_id` (`user_id`), CONSTRAINT `nails_email_archive_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `nails_user` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `nails_email_archive_link`;
CREATE TABLE `nails_email_archive_link` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `email_id` int(11) unsigned NOT NULL, `url` varchar(500) NOT NULL DEFAULT '', `title` varchar(255) DEFAULT NULL, `created` datetime NOT NULL, `is_html` tinyint(1) unsigned NOT NULL, PRIMARY KEY (`id`), KEY `email_id` (`email_id`), CONSTRAINT `nails_email_archive_link_ibfk_1` FOREIGN KEY (`email_id`) REFERENCES `nails_email_archive` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `nails_email_archive_track_link`;
CREATE TABLE `nails_email_archive_track_link` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `email_id` int(11) unsigned NOT NULL, `link_id` int(11) unsigned NOT NULL, `user_id` int(11) unsigned DEFAULT NULL, `created` datetime NOT NULL, PRIMARY KEY (`id`), KEY `email_id` (`email_id`), KEY `link_id` (`link_id`), KEY `user_id` (`user_id`), CONSTRAINT `nails_email_archive_track_link_ibfk_1` FOREIGN KEY (`email_id`) REFERENCES `nails_email_archive` (`id`) ON DELETE CASCADE, CONSTRAINT `nails_email_archive_track_link_ibfk_2` FOREIGN KEY (`link_id`) REFERENCES `nails_email_archive_link` (`id`) ON DELETE CASCADE, CONSTRAINT `nails_email_archive_track_link_ibfk_3` FOREIGN KEY (`user_id`) REFERENCES `nails_user` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE IF EXISTS `nails_email_archive_track_open`;
CREATE TABLE `nails_email_archive_track_open` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `email_id` int(11) unsigned NOT NULL, `user_id` int(11) unsigned DEFAULT NULL, `created` datetime NOT NULL, PRIMARY KEY (`id`), KEY `email_id` (`email_id`), KEY `user_id` (`user_id`), CONSTRAINT `nails_email_archive_track_open_ibfk_1` FOREIGN KEY (`email_id`) REFERENCES `nails_email_archive` (`id`) ON DELETE CASCADE, CONSTRAINT `nails_email_archive_track_open_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `nails_user` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8;